server:
  port: 8445



spring:
  application:
    name: serviceUcenter

  shardingsphere:
    # 默认的库
    # 绑定的表 不配置也没找出啥问题

    # 是否打印sql
    props:
      sql:
        show: true
    datasource:
      # 有几个库
      names: db1,db2
      # 库1 的配置
      db1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/microservice?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
        username: root
        password: 931986
      # 库2 的配置
      db2:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/microservice_slave1?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
        username: root
        password: 931986
#      db3:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://localhost:3306/microservice_slave2?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
#        username: root
#        password: 931986
#        读写分离a
          # 默认的库



#    masterslave:
#      master-data-source-name: db1
#      slave-data-source-names: db2
#      name: ms
#      load-balance-algorithm-type: round_robin
  #    sharding:
#      default-data-source-name: db1





  #      sharding.jdbc.config.masterslave.name=ms
  #sharding.jdbc.config.masterslave.master-data-source-name=master
  #sharding.jdbc.config.masterslave.slave-data-source-names=slave0,slave1




  #    nacos
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #nacos服务地址

  jackson: #返回json的全局时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8




mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapperLocations: classpath:**/xml/*.xml
