#server:
#  # 端口
#  port: 18082
#
#spring:
#  application:
#    name: testName
#  cloud:
#    nacos:
#      discovery:
#        # 指定nacos server的地址
#        server-addr: 127.0.0.1:8848
server:
  port: 9001
spring:
  application:
    name: nacos-server #服务名
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #nacos服务地址
#        namespace: f99717b6-4b29-443a-afac-c949d634e648 #命名空间,在nacos界面上操作新增空间名称
